#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : paho.mqtt.c
Version  : 1.3.12
Release  : 15
URL      : https://github.com/eclipse/paho.mqtt.c/archive/v1.3.12/paho.mqtt.c-1.3.12.tar.gz
Source0  : https://github.com/eclipse/paho.mqtt.c/archive/v1.3.12/paho.mqtt.c-1.3.12.tar.gz
Summary  : MQTT C Client
Group    : Development/Tools
License  : BSD-3-Clause EPL-1.0 EPL-2.0
Requires: paho.mqtt.c-bin = %{version}-%{release}
Requires: paho.mqtt.c-lib = %{version}-%{release}
Requires: paho.mqtt.c-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : openssl-dev
BuildRequires : pkgconfig(openssl)

%description
The Paho MQTT C Client is a fully fledged MQTT client written in ANSI standard C.

%package bin
Summary: bin components for the paho.mqtt.c package.
Group: Binaries
Requires: paho.mqtt.c-license = %{version}-%{release}

%description bin
bin components for the paho.mqtt.c package.


%package dev
Summary: dev components for the paho.mqtt.c package.
Group: Development
Requires: paho.mqtt.c-lib = %{version}-%{release}
Requires: paho.mqtt.c-bin = %{version}-%{release}
Provides: paho.mqtt.c-devel = %{version}-%{release}
Requires: paho.mqtt.c = %{version}-%{release}

%description dev
dev components for the paho.mqtt.c package.


%package lib
Summary: lib components for the paho.mqtt.c package.
Group: Libraries
Requires: paho.mqtt.c-license = %{version}-%{release}

%description lib
lib components for the paho.mqtt.c package.


%package license
Summary: license components for the paho.mqtt.c package.
Group: Default

%description license
license components for the paho.mqtt.c package.


%prep
%setup -q -n paho.mqtt.c-1.3.12
cd %{_builddir}/paho.mqtt.c-1.3.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672190969
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake .. -DPAHO_WITH_SSL=true \
-DPAHO_BUILD_SAMPLES=false \
-DPAHO_ENABLE_CPACK=false \
-DPAHO_ENABLE_TESTING=true
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1672190969
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/paho.mqtt.c
cp %{_builddir}/paho.mqtt.c-%{version}/edl-v10 %{buildroot}/usr/share/package-licenses/paho.mqtt.c/03b5669874cbaabe055c6d130446ade35b3f8c65
cp %{_builddir}/paho.mqtt.c-%{version}/epl-v20 %{buildroot}/usr/share/package-licenses/paho.mqtt.c/b086d72d0fe9af38418dab524fe76eea3cb1eec3
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/usr/share/doc/Eclipse\ Paho\ C/*.c

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/MQTTVersion

%files dev
%defattr(-,root,root,-)
/usr/include/MQTTAsync.h
/usr/include/MQTTClient.h
/usr/include/MQTTClientPersistence.h
/usr/include/MQTTExportDeclarations.h
/usr/include/MQTTProperties.h
/usr/include/MQTTReasonCodes.h
/usr/include/MQTTSubscribeOpts.h
/usr/lib64/cmake/eclipse-paho-mqtt-c/eclipse-paho-mqtt-cConfig-relwithdebinfo.cmake
/usr/lib64/cmake/eclipse-paho-mqtt-c/eclipse-paho-mqtt-cConfig.cmake
/usr/lib64/cmake/eclipse-paho-mqtt-c/eclipse-paho-mqtt-cConfigVersion.cmake
/usr/lib64/libpaho-mqtt3a.so
/usr/lib64/libpaho-mqtt3as.so
/usr/lib64/libpaho-mqtt3c.so
/usr/lib64/libpaho-mqtt3cs.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpaho-mqtt3a.so.1
/usr/lib64/libpaho-mqtt3a.so.1.3.11
/usr/lib64/libpaho-mqtt3as.so.1
/usr/lib64/libpaho-mqtt3as.so.1.3.11
/usr/lib64/libpaho-mqtt3c.so.1
/usr/lib64/libpaho-mqtt3c.so.1.3.11
/usr/lib64/libpaho-mqtt3cs.so.1
/usr/lib64/libpaho-mqtt3cs.so.1.3.11

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/paho.mqtt.c/03b5669874cbaabe055c6d130446ade35b3f8c65
/usr/share/package-licenses/paho.mqtt.c/b086d72d0fe9af38418dab524fe76eea3cb1eec3
