#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : paho.mqtt.c
Version  : 1.3.1
Release  : 6
URL      : https://github.com/eclipse/paho.mqtt.c/archive/v1.3.1/paho.mqtt.c-1.3.1.tar.gz
Source0  : https://github.com/eclipse/paho.mqtt.c/archive/v1.3.1/paho.mqtt.c-1.3.1.tar.gz
Summary  : MQTT C Client
Group    : Development/Tools
License  : BSD-3-Clause EPL-1.0
Requires: paho.mqtt.c-bin = %{version}-%{release}
Requires: paho.mqtt.c-lib = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-mvn
BuildRequires : doxygen
BuildRequires : pkgconfig(openssl)

%description
The Paho MQTT C Client is a fully fledged MQTT client written in ANSI standard C.

%package bin
Summary: bin components for the paho.mqtt.c package.
Group: Binaries

%description bin
bin components for the paho.mqtt.c package.


%package dev
Summary: dev components for the paho.mqtt.c package.
Group: Development
Requires: paho.mqtt.c-lib = %{version}-%{release}
Requires: paho.mqtt.c-bin = %{version}-%{release}
Provides: paho.mqtt.c-devel = %{version}-%{release}
Requires: paho.mqtt.c = %{version}-%{release}

%description dev
dev components for the paho.mqtt.c package.


%package lib
Summary: lib components for the paho.mqtt.c package.
Group: Libraries

%description lib
lib components for the paho.mqtt.c package.


%prep
%setup -q -n paho.mqtt.c-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571181949
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DPAHO_WITH_SSL=true \
-DPAHO_BUILD_SAMPLES=false \
-DPAHO_ENABLE_CPACK=false \
-DPAHO_ENABLE_TESTING=true
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1571181949
rm -rf %{buildroot}
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}/usr/share/doc/Eclipse\ Paho\ C/*.c

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/MQTTVersion

%files dev
%defattr(-,root,root,-)
/usr/include/MQTTAsync.h
/usr/include/MQTTClient.h
/usr/include/MQTTClientPersistence.h
/usr/include/MQTTProperties.h
/usr/include/MQTTReasonCodes.h
/usr/include/MQTTSubscribeOpts.h
/usr/lib64/libpaho-mqtt3a.so
/usr/lib64/libpaho-mqtt3as.so
/usr/lib64/libpaho-mqtt3c.so
/usr/lib64/libpaho-mqtt3cs.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpaho-mqtt3a.so.1
/usr/lib64/libpaho-mqtt3a.so.1.3.1
/usr/lib64/libpaho-mqtt3as.so.1
/usr/lib64/libpaho-mqtt3as.so.1.3.1
/usr/lib64/libpaho-mqtt3c.so.1
/usr/lib64/libpaho-mqtt3c.so.1.3.1
/usr/lib64/libpaho-mqtt3cs.so.1
/usr/lib64/libpaho-mqtt3cs.so.1.3.1
